import { TemplateCard } from "@/types";

export const TEMPLATE_CARDS: TemplateCard[] = [
  {
    id: "tshirt",
    category: "T-shirt",
    description:
      "Complete tech pack for cut-and-sew T-shirts. Covers crew neck, V-neck, and oversized silhouettes with full measurement spec sheets.",
    pages: [
      "Cover page & brand details",
      "Technical flat sketch (front & back)",
      "Measurement spec sheet",
      "Construction details & stitch types",
      "Fabric & trim specifications",
      "Label & packaging requirements",
      "Colorway breakdown",
      "Grading chart (XS–XXL)",
    ],
    pdfFile: "/templates/pdf/tshirt-tech-pack.pdf",
    illustratorFile: "/templates/illustrator/tshirt-tech-pack.ai",
    spreadsheetFile: "/templates/spreadsheets/tshirt-spec-sheet.xlsx",
  },
  {
    id: "hoodie",
    category: "Hoodie",
    description:
      "Tech pack for pullover and zip-up hoodies. Includes drawstring, pocket, and ribbing specifications with full garment measurements.",
    pages: [
      "Cover page & brand details",
      "Technical flat sketch (front, back, detail)",
      "Measurement spec sheet",
      "Drawstring & hardware specs",
      "Pocket construction detail",
      "Ribbing & hem specifications",
      "Fabric & trim specifications",
      "Label & packaging requirements",
      "Grading chart (XS–XXL)",
    ],
    pdfFile: "/templates/pdf/hoodie-tech-pack.pdf",
    illustratorFile: "/templates/illustrator/hoodie-tech-pack.ai",
    spreadsheetFile: "/templates/spreadsheets/hoodie-spec-sheet.xlsx",
  },
  {
    id: "sweatpants",
    category: "Sweatpants",
    description:
      "Tech pack for fleece and French terry sweatpants. Covers waistband, cuff, pocket, and inseam specs.",
    pages: [
      "Cover page & brand details",
      "Technical flat sketch (front & back)",
      "Measurement spec sheet",
      "Waistband & drawstring detail",
      "Pocket construction detail",
      "Cuff & hem specifications",
      "Fabric & trim specifications",
      "Label & packaging requirements",
      "Grading chart (XS–XXL)",
    ],
    pdfFile: "/templates/pdf/sweatpants-tech-pack.pdf",
    illustratorFile: "/templates/illustrator/sweatpants-tech-pack.ai",
    spreadsheetFile: "/templates/spreadsheets/sweatpants-spec-sheet.xlsx",
  },
  {
    id: "denim",
    category: "Denim",
    description:
      "Comprehensive denim tech pack covering jeans, shorts, and jackets. Includes pocket placement, rivets, hardware, and wash specifications.",
    pages: [
      "Cover page & brand details",
      "Technical flat sketch (front, back, details)",
      "Measurement spec sheet",
      "Pocket placement & construction",
      "Rivet, button & zipper specifications",
      "Wash & treatment instructions",
      "Fabric weight & composition",
      "Stitching & thread color specs",
      "Label & packaging requirements",
      "Grading chart (24–38 or XS–XXL)",
    ],
    pdfFile: "/templates/pdf/denim-tech-pack.pdf",
    illustratorFile: "/templates/illustrator/denim-tech-pack.ai",
    spreadsheetFile: "/templates/spreadsheets/denim-spec-sheet.xlsx",
  },
  {
    id: "jacket",
    category: "Jacket",
    description:
      "Tech pack for outerwear and light jackets. Covers zipper, lining, shell, and interlining specs with full construction callouts.",
    pages: [
      "Cover page & brand details",
      "Technical flat sketch (front, back, lining)",
      "Measurement spec sheet",
      "Shell & lining fabric specs",
      "Zipper & hardware specifications",
      "Collar & hood construction detail",
      "Pocket construction detail",
      "Interlining & padding specs (if applicable)",
      "Label & packaging requirements",
      "Grading chart (XS–XXL)",
    ],
    pdfFile: "/templates/pdf/jacket-tech-pack.pdf",
    illustratorFile: "/templates/illustrator/jacket-tech-pack.ai",
    spreadsheetFile: "/templates/spreadsheets/jacket-spec-sheet.xlsx",
  },
];
